chore(ci): Update workflows and scripts to test against staging branch instead.
Signed-off-by: Andrei Jiroh Eugenio Halili <andreijiroh@madebythepins.tk>

diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -6,11 +6,11 @@ echo "==> Fetching and pulling updates…"
 git fetch --all
 if [ $? -eq 0 ]; then
    echo "✔ Successfully fetched remote updates!"
-   git pull origin main
-   if [ $? -eq 0]; then
+   git pull origin staging
+   if [ $? -eq 0 ]; then
       echo "✔ Successfully pulled remote changes!"
    else
-      echo "❌ Git just gave up because errors are fired up or merge conflicts are detected."
+      echo "❌ Git just gave up because errors are fired up or merge conflicts (possibly unrelated branches' histories) are detected."
    fi
 else
    echo "❌ 'git fetch' fired up some errors. If issue presists, store the runtime logs above and file a new issue in GitHub/GitLab.com"
